name: environment
channels:
  - defaults
  - conda-forge
  - anaconda-fusion
dependencies:
  - numpy
  - cartopy
  - nc-time-axis
  - xarray
  - distributed
  - pandas
  - matplotlib
  - h5netcdf
  - ipykernel
  - ipywidgets
  - netcdf-fortran
  - nodejs
  - numcodecs
  - python
  - jupyterlab
  - matplotlib-inline
  - netcdf4
  - python-graphviz
  - metpy
  - siphon
  - scikit-learn
  - ipympl
  - datashader
  - geoviews
  - cmocean
  - pytest
  - pyresample
  - nbdime
  - gsw
  - iris
  - fsspec
  - altair
  - vega_datasets
  - plotnine
  - scikit-image
  - aospy
  - geopandas
  - setuptools
  - build
  - hatchling
  - twine
  - pip
